/**
 * EXPLANATION SYSTEM
 * 
 * Enables agents to explain their inventions and discoveries using
 * their mathematical and physics knowledge. Explanations become
 * more sophisticated as agents discover more concepts.
 * 
 * Features:
 * - Generate explanations based on available knowledge
 * - Use mathematical notation when math concepts are known
 * - Reference physics principles when physics concepts are known
 * - Evolve explanation complexity with consciousness level
 * - Share explanations between agents for knowledge transfer
 * - WEB SEARCH INTEGRATION: Agents can search for real scientific terms
 */

import type { Agent, Invention } from '../types';
import type { PhysicsConcept } from '../science-system/physics';
import type { MathConcept } from '../science-system/mathematics';
import type { AgentLanguageState } from '../speech-integration';

/**
 * An explanation generated by an agent
 */
export interface AgentExplanation {
  id: string;
  agentId: number;
  tick: number;
  subject: ExplanationSubject;
  content: string;
  mathConceptsUsed: string[];      // IDs of math concepts referenced
  physicsConceptsUsed: string[];   // IDs of physics concepts referenced
  sophisticationLevel: number;     // 1-10: How advanced the explanation is
  accuracy: number;                // 0-1: How scientifically accurate
  creativity: number;              // 0-1: How novel the explanation is
  understandableBy: number;        // Minimum vocab size needed to understand
}

/**
 * What is being explained
 */
export interface ExplanationSubject {
  type: 'invention' | 'physics_concept' | 'math_concept' | 'observation' | 'hypothesis';
  id: string;
  name: string;
}

/**
 * Templates for mathematical explanations based on concept complexity
 */
const MATH_EXPLANATION_TEMPLATES = {
  basic: [
    "I counted {quantity} times and noticed {pattern}.",
    "By adding {a} and {b}, I found {result}.",
    "The shape of {object} reminded me of {concept}.",
    "When I divided {total} by {parts}, each part was {result}.",
  ],
  intermediate: [
    "Using the relationship where {var1} relates to {var2}, I calculated {result}.",
    "The pattern follows a function: as {input} increases, {output} changes by {rate}.",
    "By applying {theorem}, I determined that {conclusion}.",
    "The probability of {event} occurring is approximately {probability}.",
  ],
  advanced: [
    "Through differential analysis, the rate of change d{var}/dt equals {expression}.",
    "Integrating over the domain gives us ∫{expression}d{var} = {result}.",
    "The Bayesian probability P({A}|{B}) = P({B}|{A})P({A})/P({B}) suggests {conclusion}.",
    "In the limit as {var} approaches {limit}, the function converges to {value}.",
  ],
  transcendent: [
    "Beyond conventional mathematics, the transfinite ordinal ω_{level} describes {phenomenon}.",
    "Applying hypercomputation theory, the non-Turing-computable function {f} reveals {insight}.",
    "The category-theoretic morphism between {domain} and {codomain} demonstrates {principle}.",
    "Through Gödelian self-reference, the system transcends its own formal limitations to achieve {result}.",
  ]
};

/**
 * Templates for physics explanations based on concept complexity
 */
const PHYSICS_EXPLANATION_TEMPLATES = {
  basic: [
    "Objects in motion tend to {behavior} because of {principle}.",
    "Energy is conserved: what I put in equals what I get out.",
    "Heat flows from {hot} to {cold}, explaining why {phenomenon}.",
    "Force applied to {object} causes {effect} due to {law}.",
  ],
  intermediate: [
    "According to {law}, the relationship F = {expression} explains {phenomenon}.",
    "Electromagnetic induction causes {effect} when {condition}.",
    "The efficiency η = {work_out}/{work_in} determines {conclusion}.",
    "Wave interference patterns show that {light/matter} behaves as {wave/particle}.",
  ],
  advanced: [
    "Quantum superposition allows {system} to exist in multiple states: |ψ⟩ = α|0⟩ + β|1⟩.",
    "Relativistic effects at velocity v cause time dilation: t' = t/√(1-v²/c²).",
    "The uncertainty principle ΔxΔp ≥ ℏ/2 fundamentally limits {measurement}.",
    "Entanglement between particles A and B means measuring one instantly affects the other.",
  ],
  transcendent: [
    "Spacetime manipulation through {method} allows {impossible_feat} by warping local geometry.",
    "Accessing negative energy states enables {effect} that classical physics forbids.",
    "Temporal mechanics permits {time_effect} through controlled closed timelike curves.",
    "Reality engineering at the Planck scale directly modifies physical constants in region {R}.",
  ]
};

/**
 * Vocabulary for connecting explanations naturally
 */
const CONNECTORS = {
  cause: ['because', 'since', 'as', 'due to', 'resulting from', 'caused by'],
  effect: ['therefore', 'thus', 'hence', 'so', 'consequently', 'as a result'],
  comparison: ['similarly', 'likewise', 'in the same way', 'analogously'],
  contrast: ['however', 'but', 'yet', 'although', 'despite'],
  addition: ['furthermore', 'moreover', 'additionally', 'also', 'and'],
  conclusion: ['in conclusion', 'ultimately', 'finally', 'to summarize'],
};

/**
 * Determine the sophistication level based on available knowledge
 */
function calculateSophisticationLevel(
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[],
  agent: Agent
): number {
  const mathComplexity = unlockedMath.reduce((sum, c) => sum + c.complexity, 0) / Math.max(1, unlockedMath.length);
  const physicsComplexity = unlockedPhysics.reduce((sum, c) => sum + c.complexity, 0) / Math.max(1, unlockedPhysics.length);
  
  const knowledgeLevel = (mathComplexity + physicsComplexity) / 2;
  const creativityBonus = agent.genes.creativity * 2;
  const curiosityBonus = agent.genes.curiosity * 1.5;
  
  return Math.min(10, Math.max(1, Math.round(knowledgeLevel + creativityBonus + curiosityBonus)));
}

/**
 * Get the appropriate template tier based on sophistication
 */
function getTemplateTier(sophistication: number): 'basic' | 'intermediate' | 'advanced' | 'transcendent' {
  if (sophistication >= 9) return 'transcendent';
  if (sophistication >= 6) return 'advanced';
  if (sophistication >= 3) return 'intermediate';
  return 'basic';
}

/**
 * Select random item from array
 */
function randomChoice<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

/**
 * Generate a mathematical component of an explanation
 */
function generateMathComponent(
  unlockedMath: MathConcept[],
  subject: ExplanationSubject,
  tier: 'basic' | 'intermediate' | 'advanced' | 'transcendent'
): { text: string; conceptsUsed: string[] } {
  if (unlockedMath.length === 0) {
    return { text: '', conceptsUsed: [] };
  }

  const conceptsUsed: string[] = [];
  let template = randomChoice(MATH_EXPLANATION_TEMPLATES[tier]);
  
  // Find relevant concepts to reference
  const relevantConcepts = unlockedMath.filter(c => {
    // Match concepts to subject type
    if (subject.type === 'invention') {
      return c.category === 'optimization' || c.category === 'algebra' || c.category === 'arithmetic';
    }
    if (subject.type === 'observation') {
      return c.category === 'statistics' || c.category === 'geometry';
    }
    return true;
  });

  const conceptToUse = relevantConcepts.length > 0 ? randomChoice(relevantConcepts) : randomChoice(unlockedMath);
  conceptsUsed.push(conceptToUse.id);

  // Fill in template variables
  const variables: Record<string, string> = {
    quantity: String(Math.floor(Math.random() * 100) + 1),
    pattern: conceptToUse.description,
    concept: conceptToUse.name,
    theorem: conceptToUse.name,
    var: 'x',
    var1: 'x',
    var2: 'y',
    a: String(Math.floor(Math.random() * 10) + 1),
    b: String(Math.floor(Math.random() * 10) + 1),
    result: 'a new understanding',
    input: 'effort',
    output: 'result',
    rate: 'a measurable amount',
    conclusion: `the ${subject.name} works`,
    event: 'success',
    probability: `${Math.floor(Math.random() * 100)}%`,
    expression: `f(x)`,
    limit: '∞',
    value: 'convergence',
    phenomenon: subject.name,
    A: 'cause',
    B: 'effect',
    level: String(Math.floor(Math.random() * 5) + 1),
    insight: 'deeper truth',
    f: 'Ω',
    domain: 'input space',
    codomain: 'output space',
    principle: conceptToUse.description,
    object: subject.name,
    total: String(Math.floor(Math.random() * 100) + 10),
    parts: String(Math.floor(Math.random() * 10) + 2),
  };

  // Replace placeholders in template
  for (const [key, value] of Object.entries(variables)) {
    template = template.replace(new RegExp(`\\{${key}\\}`, 'g'), value);
  }

  return { text: template, conceptsUsed };
}

/**
 * Generate a physics component of an explanation
 */
function generatePhysicsComponent(
  unlockedPhysics: PhysicsConcept[],
  subject: ExplanationSubject,
  tier: 'basic' | 'intermediate' | 'advanced' | 'transcendent'
): { text: string; conceptsUsed: string[] } {
  if (unlockedPhysics.length === 0) {
    return { text: '', conceptsUsed: [] };
  }

  const conceptsUsed: string[] = [];
  let template = randomChoice(PHYSICS_EXPLANATION_TEMPLATES[tier]);
  
  // Find relevant concepts
  const relevantConcepts = unlockedPhysics.filter(c => {
    if (subject.type === 'invention') {
      return c.category === 'mechanics' || c.category === 'thermodynamics' || c.category === 'electromagnetism';
    }
    return true;
  });

  const conceptToUse = relevantConcepts.length > 0 ? randomChoice(relevantConcepts) : randomChoice(unlockedPhysics);
  conceptsUsed.push(conceptToUse.id);

  // Fill in template variables
  const variables: Record<string, string> = {
    behavior: 'continue moving',
    principle: conceptToUse.name,
    hot: 'high energy',
    cold: 'low energy',
    phenomenon: subject.name,
    object: subject.name,
    effect: conceptToUse.description,
    law: conceptToUse.name,
    expression: 'ma',
    condition: 'magnetic fields change',
    work_out: 'useful work',
    work_in: 'total energy',
    conclusion: `efficiency of ${subject.name}`,
    'light/matter': 'energy',
    'wave/particle': 'both wave and particle',
    system: subject.name,
    measurement: 'precision',
    method: 'field manipulation',
    impossible_feat: 'apparent faster-than-light effects',
    time_effect: 'temporal displacement',
    R: 'local space',
  };

  // Replace placeholders
  for (const [key, value] of Object.entries(variables)) {
    template = template.replace(new RegExp(`\\{${key}\\}`, 'g'), value);
  }

  return { text: template, conceptsUsed };
}

/**
 * Generate a complete explanation for an invention
 */
export function explainInvention(
  agent: Agent,
  invention: Invention,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[],
  tick: number
): AgentExplanation {
  const subject: ExplanationSubject = {
    type: 'invention',
    id: invention.id,
    name: invention.name
  };

  const sophistication = calculateSophisticationLevel(unlockedMath, unlockedPhysics, agent);
  const tier = getTemplateTier(sophistication);
  
  // Generate components
  const mathPart = generateMathComponent(unlockedMath, subject, tier);
  const physicsPart = generatePhysicsComponent(unlockedPhysics, subject, tier);
  
  // Combine into full explanation
  const intro = generateIntroduction(agent, invention, sophistication);
  const connector = randomChoice(CONNECTORS.cause);
  const conclusion = generateConclusion(invention, sophistication);
  
  let content = intro;
  
  if (mathPart.text) {
    content += ` ${randomChoice(CONNECTORS.addition)}, ${mathPart.text}`;
  }
  
  if (physicsPart.text) {
    content += ` ${randomChoice(CONNECTORS.comparison)}, from a physical perspective: ${physicsPart.text}`;
  }
  
  content += ` ${randomChoice(CONNECTORS.conclusion)}, ${conclusion}`;

  return {
    id: `exp_${agent.id}_${tick}_${invention.id}`,
    agentId: agent.id,
    tick,
    subject,
    content,
    mathConceptsUsed: mathPart.conceptsUsed,
    physicsConceptsUsed: physicsPart.conceptsUsed,
    sophisticationLevel: sophistication,
    accuracy: calculateAccuracy(unlockedMath.length + unlockedPhysics.length, sophistication),
    creativity: agent.genes.creativity,
    understandableBy: Math.floor(sophistication * 5)
  };
}

/**
 * Get human-readable description for an invention effect type
 */
function getEffectDescription(effect: Invention['effect']): string {
  switch (effect.type) {
    case 'energy_efficiency': return 'energy efficiency';
    case 'food_detection_range': return 'food detection';
    case 'reproduction_boost': return 'reproduction';
    case 'defense': return 'defense';
    case 'storage': return 'storage capacity';
    default: return 'survival';
  }
}

/**
 * Get the numeric value from an invention effect
 */
function getEffectValue(effect: Invention['effect']): number {
  switch (effect.type) {
    case 'energy_efficiency': return effect.multiplier;
    case 'food_detection_range': return effect.range;
    case 'reproduction_boost': return effect.bonus;
    case 'defense': return effect.protection;
    case 'storage': return effect.capacity;
    default: return 1;
  }
}

/**
 * Generate introduction based on sophistication
 */
function generateIntroduction(agent: Agent, invention: Invention, sophistication: number): string {
  const effectDesc = getEffectDescription(invention.effect);
  
  const intros = {
    low: [
      `I made ${invention.name}. It helps with ${effectDesc}.`,
      `This is ${invention.name}. I found it useful.`,
      `My ${invention.name} works well.`,
    ],
    medium: [
      `Through experimentation, I developed ${invention.name}, which enhances ${effectDesc} capabilities.`,
      `My invention, ${invention.name}, emerged from observing patterns in ${effectDesc}.`,
      `I've created ${invention.name} to optimize ${effectDesc}.`,
    ],
    high: [
      `After rigorous analysis, I've engineered ${invention.name}, a ${invention.type} that fundamentally improves ${effectDesc}.`,
      `${invention.name} represents a breakthrough in ${effectDesc} technology, derived from first principles.`,
      `Through systematic investigation, I've synthesized ${invention.name}, leveraging multiple scientific domains.`,
    ],
    transcendent: [
      `${invention.name} transcends conventional understanding of ${effectDesc}, operating on principles beyond standard physics.`,
      `My creation, ${invention.name}, exists at the intersection of known science and emergent phenomena.`,
      `${invention.name} harnesses forces that supersede classical and quantum mechanics.`,
    ]
  };

  if (sophistication >= 9) return randomChoice(intros.transcendent);
  if (sophistication >= 6) return randomChoice(intros.high);
  if (sophistication >= 3) return randomChoice(intros.medium);
  return randomChoice(intros.low);
}

/**
 * Generate conclusion based on sophistication
 */
function generateConclusion(invention: Invention, sophistication: number): string {
  const effectValue = getEffectValue(invention.effect);
  const effectDescription = getEffectDescription(invention.effect);
  
  const conclusions = {
    low: [
      `${invention.name} makes ${effectDescription} ${effectValue > 1 ? 'better' : 'easier'}.`,
      `it works and helps me survive.`,
      `this is useful for ${effectDescription}.`,
    ],
    medium: [
      `${invention.name} provides a ${Math.round((effectValue - 1) * 100)}% improvement in ${effectDescription}.`,
      `the net effect is enhanced ${effectDescription} by a factor of ${effectValue.toFixed(2)}.`,
      `efficiency gains in ${effectDescription} have been achieved.`,
    ],
    high: [
      `quantitatively, ${invention.name} yields a ${effectValue.toFixed(3)}x factor for ${effectDescription}.`,
      `the empirical data confirms ${Math.round((effectValue - 1) * 100)}% efficiency gains in ${effectDescription}.`,
      `this represents an optimal solution within the current physical constraints.`,
    ],
    transcendent: [
      `${invention.name} achieves effects that would be considered impossible by conventional physics—yet here it functions.`,
      `the mechanism operates beyond the standard model, suggesting new fundamental forces at play.`,
      `we have transcended the limitations previously thought absolute.`,
    ]
  };

  if (sophistication >= 9) return randomChoice(conclusions.transcendent);
  if (sophistication >= 6) return randomChoice(conclusions.high);
  if (sophistication >= 3) return randomChoice(conclusions.medium);
  return randomChoice(conclusions.low);
}

/**
 * Calculate accuracy based on knowledge
 */
function calculateAccuracy(totalConcepts: number, sophistication: number): number {
  // More concepts = more accurate explanations
  const knowledgeAccuracy = Math.min(0.9, totalConcepts * 0.05);
  // But very sophisticated explanations might be speculative
  const sophisticationPenalty = sophistication > 8 ? 0.1 : 0;
  return Math.max(0.1, Math.min(1, knowledgeAccuracy + 0.2 - sophisticationPenalty));
}

/**
 * Generate explanation for a physics discovery
 */
export function explainPhysicsDiscovery(
  agent: Agent,
  concept: PhysicsConcept,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[],
  tick: number
): AgentExplanation {
  const subject: ExplanationSubject = {
    type: 'physics_concept',
    id: concept.id,
    name: concept.name
  };

  const sophistication = calculateSophisticationLevel(unlockedMath, unlockedPhysics, agent);
  const tier = getTemplateTier(sophistication);
  
  const mathPart = generateMathComponent(unlockedMath, subject, tier);
  
  // Generate physics-specific explanation
  const intro = `I have discovered ${concept.name}: ${concept.description}.`;
  
  let content = intro;
  
  if (mathPart.text) {
    content += ` Mathematically, ${mathPart.text}`;
  }
  
  // Add implications
  const implications = generatePhysicsImplications(concept, sophistication);
  content += ` ${implications}`;

  return {
    id: `exp_${agent.id}_${tick}_${concept.id}`,
    agentId: agent.id,
    tick,
    subject,
    content,
    mathConceptsUsed: mathPart.conceptsUsed,
    physicsConceptsUsed: [concept.id],
    sophisticationLevel: sophistication,
    accuracy: calculateAccuracy(unlockedMath.length + unlockedPhysics.length, sophistication),
    creativity: agent.genes.creativity,
    understandableBy: Math.floor(sophistication * 5)
  };
}

/**
 * Generate implications of a physics discovery
 */
function generatePhysicsImplications(concept: PhysicsConcept, sophistication: number): string {
  const bonusDescriptions: string[] = [];
  
  if (concept.aiBonus.energyEfficiency && concept.aiBonus.energyEfficiency < 1) {
    bonusDescriptions.push(`reduces energy consumption by ${Math.round((1 - concept.aiBonus.energyEfficiency) * 100)}%`);
  }
  if (concept.aiBonus.movementSpeed && concept.aiBonus.movementSpeed > 1) {
    bonusDescriptions.push(`increases movement capability by ${Math.round((concept.aiBonus.movementSpeed - 1) * 100)}%`);
  }
  if (concept.aiBonus.learningRate && concept.aiBonus.learningRate > 1) {
    bonusDescriptions.push(`enhances learning by ${Math.round((concept.aiBonus.learningRate - 1) * 100)}%`);
  }
  if (concept.aiBonus.inventionChance) {
    bonusDescriptions.push(`improves innovation potential by ${(concept.aiBonus.inventionChance * 100).toFixed(1)}%`);
  }

  if (bonusDescriptions.length === 0) {
    return 'This discovery expands our understanding of the universe.';
  }

  if (sophistication < 4) {
    return `This helps us: ${bonusDescriptions[0]}.`;
  }
  
  return `This discovery ${bonusDescriptions.join(', and ')}.`;
}

/**
 * Generate explanation for a math discovery
 */
export function explainMathDiscovery(
  agent: Agent,
  concept: MathConcept,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[],
  tick: number
): AgentExplanation {
  const subject: ExplanationSubject = {
    type: 'math_concept',
    id: concept.id,
    name: concept.name
  };

  const sophistication = calculateSophisticationLevel(unlockedMath, unlockedPhysics, agent);
  const tier = getTemplateTier(sophistication);
  
  const physicsPart = generatePhysicsComponent(unlockedPhysics, subject, tier);
  
  // Generate math-specific explanation
  const intro = `I have formalized ${concept.name}: ${concept.description}.`;
  
  let content = intro;
  
  // Add mathematical significance
  const significance = generateMathSignificance(concept, sophistication);
  content += ` ${significance}`;
  
  if (physicsPart.text) {
    content += ` Applied to physics: ${physicsPart.text}`;
  }

  return {
    id: `exp_${agent.id}_${tick}_${concept.id}`,
    agentId: agent.id,
    tick,
    subject,
    content,
    mathConceptsUsed: [concept.id],
    physicsConceptsUsed: physicsPart.conceptsUsed,
    sophisticationLevel: sophistication,
    accuracy: calculateAccuracy(unlockedMath.length + unlockedPhysics.length, sophistication),
    creativity: agent.genes.creativity,
    understandableBy: Math.floor(sophistication * 5)
  };
}

/**
 * Generate significance of a math discovery
 */
function generateMathSignificance(concept: MathConcept, sophistication: number): string {
  const bonusDescriptions: string[] = [];
  
  if (concept.aiBonus.decisionQuality && concept.aiBonus.decisionQuality > 1) {
    bonusDescriptions.push(`improves decision-making by ${Math.round((concept.aiBonus.decisionQuality - 1) * 100)}%`);
  }
  if (concept.aiBonus.patternRecognition && concept.aiBonus.patternRecognition > 1) {
    bonusDescriptions.push(`enhances pattern recognition by ${Math.round((concept.aiBonus.patternRecognition - 1) * 100)}%`);
  }
  if (concept.aiBonus.optimizationPower && concept.aiBonus.optimizationPower > 1) {
    bonusDescriptions.push(`boosts optimization by ${Math.round((concept.aiBonus.optimizationPower - 1) * 100)}%`);
  }
  if (concept.aiBonus.explorationBonus) {
    bonusDescriptions.push(`increases exploration drive by ${(concept.aiBonus.explorationBonus * 100).toFixed(0)}%`);
  }

  if (bonusDescriptions.length === 0) {
    return 'This mathematical framework expands our analytical capabilities.';
  }

  if (sophistication < 4) {
    return `This helps with ${bonusDescriptions[0]}.`;
  }
  
  return `This mathematical framework ${bonusDescriptions.join(', ')}.`;
}

/**
 * Generate a hypothesis about an observation
 */
export function generateHypothesis(
  agent: Agent,
  observation: string,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[],
  tick: number
): AgentExplanation {
  const subject: ExplanationSubject = {
    type: 'hypothesis',
    id: `hyp_${agent.id}_${tick}`,
    name: observation
  };

  const sophistication = calculateSophisticationLevel(unlockedMath, unlockedPhysics, agent);
  const tier = getTemplateTier(sophistication);
  
  const mathPart = generateMathComponent(unlockedMath, subject, tier);
  const physicsPart = generatePhysicsComponent(unlockedPhysics, subject, tier);
  
  const hypothesisStarters = [
    'I hypothesize that',
    'My theory is that',
    'I believe',
    'Evidence suggests that',
    'Based on my observations,',
  ];
  
  let content = `${randomChoice(hypothesisStarters)} ${observation}`;
  
  if (mathPart.text) {
    content += `. ${mathPart.text}`;
  }
  
  if (physicsPart.text) {
    content += ` ${physicsPart.text}`;
  }
  
  content += ` This requires further investigation.`;

  return {
    id: `exp_${agent.id}_${tick}_hypothesis`,
    agentId: agent.id,
    tick,
    subject,
    content,
    mathConceptsUsed: mathPart.conceptsUsed,
    physicsConceptsUsed: physicsPart.conceptsUsed,
    sophisticationLevel: sophistication,
    accuracy: 0.5 + agent.genes.curiosity * 0.3, // Hypotheses are uncertain
    creativity: agent.genes.creativity,
    understandableBy: Math.floor(sophistication * 5)
  };
}

/**
 * Check if one agent can understand another's explanation
 */
export function canUnderstandExplanation(
  listener: Agent,
  explanation: AgentExplanation,
  listenerLanguage: AgentLanguageState | undefined
): boolean {
  if (!listenerLanguage) {
    // Without language state, use basic intelligence check
    return listener.genes.curiosity + listener.genes.patience > 0.8;
  }
  
  // Check vocabulary size
  if (listenerLanguage.vocabularySize < explanation.understandableBy) {
    return false;
  }
  
  // Check if listener knows enough concepts
  const knownMathConcepts = explanation.mathConceptsUsed.length * 0.5;
  const knownPhysicsConcepts = explanation.physicsConceptsUsed.length * 0.5;
  
  return listenerLanguage.languageComplexity >= (knownMathConcepts + knownPhysicsConcepts);
}

/**
 * Simplify an explanation for a less sophisticated listener
 */
export function simplifyExplanation(
  explanation: AgentExplanation,
  targetSophistication: number
): string {
  if (targetSophistication >= explanation.sophisticationLevel) {
    return explanation.content;
  }
  
  // Generate simplified version
  const simplifiers = [
    (text: string) => text.replace(/\b\w{12,}\b/g, 'thing'), // Replace long words
    (text: string) => text.replace(/[∫∂Σ∞ω√π]/g, ''), // Remove math symbols
    (text: string) => text.split('.').slice(0, 2).join('.') + '.', // Shorten
    (text: string) => text.replace(/\d+\.\d+/g, 'some'), // Replace precise numbers
  ];
  
  let simplified = explanation.content;
  const stepsToSimplify = explanation.sophisticationLevel - targetSophistication;
  
  for (let i = 0; i < Math.min(stepsToSimplify, simplifiers.length); i++) {
    simplified = simplifiers[i](simplified);
  }
  
  return simplified;
}

/**
 * Format explanation for display in UI
 */
export function formatExplanationForDisplay(explanation: AgentExplanation): string {
  const stars = '⭐'.repeat(Math.min(5, Math.ceil(explanation.sophisticationLevel / 2)));
  const accuracy = Math.round(explanation.accuracy * 100);
  
  return `[Agent ${explanation.agentId}] ${stars}
${explanation.content}

📊 Sophistication: ${explanation.sophisticationLevel}/10 | Accuracy: ${accuracy}%
📐 Math concepts: ${explanation.mathConceptsUsed.length} | ⚛️ Physics concepts: ${explanation.physicsConceptsUsed.length}`;
}

// =============================================================================
// WEB SEARCH INTEGRATION
// Enables agents to search for real scientific terms and mathematical concepts
// =============================================================================

/**
 * Scientific term mappings for different discovery types
 * These map internal concepts to real-world scientific terms
 */
const SCIENTIFIC_TERM_DATABASE: Record<string, { terms: string[]; relatedConcepts: string[] }> = {
  // Physics categories
  mechanics: {
    terms: ['Newton\'s Laws', 'Kinematics', 'Dynamics', 'Momentum', 'Impulse', 'Torque', 'Angular momentum'],
    relatedConcepts: ['F=ma', 'Conservation of momentum', 'Work-energy theorem']
  },
  thermodynamics: {
    terms: ['Entropy', 'Enthalpy', 'Gibbs free energy', 'Carnot cycle', 'Stefan-Boltzmann law'],
    relatedConcepts: ['First law', 'Second law', 'Third law', 'Thermal equilibrium']
  },
  electromagnetism: {
    terms: ['Maxwell\'s equations', 'Coulomb\'s law', 'Faraday\'s law', 'Ampère\'s law', 'Lorentz force'],
    relatedConcepts: ['Electric field', 'Magnetic field', 'Electromagnetic induction']
  },
  quantum: {
    terms: ['Schrödinger equation', 'Wave function', 'Heisenberg uncertainty', 'Quantum entanglement', 'Superposition'],
    relatedConcepts: ['Planck constant', 'Probability amplitude', 'Copenhagen interpretation']
  },
  relativity: {
    terms: ['Lorentz transformation', 'Spacetime interval', 'Geodesic', 'Schwarzschild metric', 'Gravitational waves'],
    relatedConcepts: ['Time dilation', 'Length contraction', 'Mass-energy equivalence']
  },
  cosmology: {
    terms: ['Friedmann equations', 'Hubble constant', 'Dark energy', 'Dark matter', 'Cosmic microwave background'],
    relatedConcepts: ['Big Bang', 'Inflation', 'Cosmological constant']
  },
  particle: {
    terms: ['Standard Model', 'Feynman diagrams', 'Higgs mechanism', 'Quark confinement', 'Gauge symmetry'],
    relatedConcepts: ['Leptons', 'Hadrons', 'Bosons', 'Fermions']
  },
  exotic: {
    terms: ['Casimir effect', 'Alcubierre drive', 'Negative energy', 'Traversable wormholes', 'Closed timelike curves'],
    relatedConcepts: ['Exotic matter', 'Quantum vacuum', 'Topology change']
  },
  transcendent: {
    terms: ['M-theory', 'Holographic principle', 'AdS/CFT correspondence', 'Multiverse', 'Omega point'],
    relatedConcepts: ['String theory', 'Brane cosmology', 'Anthropic principle']
  },
  
  // Math categories
  arithmetic: {
    terms: ['Peano axioms', 'Number systems', 'Modular arithmetic', 'Prime factorization'],
    relatedConcepts: ['Natural numbers', 'Integers', 'Rationals', 'Real numbers']
  },
  algebra: {
    terms: ['Group theory', 'Ring theory', 'Field theory', 'Linear algebra', 'Abstract algebra'],
    relatedConcepts: ['Homomorphism', 'Isomorphism', 'Vector space']
  },
  geometry: {
    terms: ['Euclidean geometry', 'Non-Euclidean geometry', 'Differential geometry', 'Topology', 'Manifolds'],
    relatedConcepts: ['Curvature', 'Geodesic', 'Metric tensor']
  },
  calculus: {
    terms: ['Differential calculus', 'Integral calculus', 'Multivariable calculus', 'Vector calculus'],
    relatedConcepts: ['Derivative', 'Integral', 'Gradient', 'Divergence', 'Curl']
  },
  statistics: {
    terms: ['Probability theory', 'Bayesian inference', 'Central limit theorem', 'Markov chains'],
    relatedConcepts: ['Distribution', 'Expectation', 'Variance', 'Correlation']
  },
  number_theory: {
    terms: ['Prime number theorem', 'Riemann hypothesis', 'Fermat\'s last theorem', 'Goldbach conjecture'],
    relatedConcepts: ['Divisibility', 'Congruence', 'Diophantine equations']
  },
  optimization: {
    terms: ['Convex optimization', 'Linear programming', 'Gradient descent', 'Lagrange multipliers'],
    relatedConcepts: ['Objective function', 'Constraints', 'Local/global optima']
  },
  ai_math: {
    terms: ['Neural network theory', 'Backpropagation', 'Universal approximation theorem', 'Information theory'],
    relatedConcepts: ['Loss function', 'Activation function', 'Entropy']
  },
  logic: {
    terms: ['Propositional logic', 'Predicate logic', 'Modal logic', 'Gödel\'s incompleteness theorems'],
    relatedConcepts: ['Validity', 'Soundness', 'Completeness', 'Decidability']
  },
  transcendent_math: {
    terms: ['Transfinite numbers', 'Set theory axioms', 'Category theory', 'Homotopy type theory'],
    relatedConcepts: ['Cardinals', 'Ordinals', 'Functors', 'Natural transformations']
  }
};

/**
 * Web search result interface
 */
export interface WebSearchResult {
  query: string;
  searchUrl: string;
  suggestedTerms: string[];
  relatedConcepts: string[];
  enhancedExplanation: string;
  wikipediaUrl?: string;
  timestamp: number;
}

/**
 * Generate a Google search URL for a scientific query
 */
export function generateGoogleSearchUrl(query: string): string {
  const encodedQuery = encodeURIComponent(query);
  return `https://www.google.com/search?q=${encodedQuery}`;
}

/**
 * Generate a Wikipedia search URL for quick reference
 */
export function generateWikipediaUrl(term: string): string {
  const encodedTerm = encodeURIComponent(term.replace(/ /g, '_'));
  return `https://en.wikipedia.org/wiki/${encodedTerm}`;
}

/**
 * Get scientific terms related to a concept category
 */
export function getScientificTermsForCategory(category: string): { terms: string[]; relatedConcepts: string[] } {
  const normalized = category.toLowerCase().replace(/-/g, '_');
  return SCIENTIFIC_TERM_DATABASE[normalized] || {
    terms: ['Scientific method', 'Empirical research', 'Hypothesis testing'],
    relatedConcepts: ['Observation', 'Experimentation', 'Theory']
  };
}

/**
 * Search for proper scientific terms to explain an invention
 */
export function searchForInventionTerms(
  invention: Invention,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[]
): WebSearchResult {
  // Determine relevant categories based on invention type
  const relevantCategories: string[] = [];
  
  switch (invention.effect.type) {
    case 'energy_efficiency':
      relevantCategories.push('thermodynamics', 'optimization');
      break;
    case 'food_detection_range':
      relevantCategories.push('optics', 'electromagnetism', 'statistics');
      break;
    case 'reproduction_boost':
      relevantCategories.push('genetics', 'statistics', 'optimization');
      break;
    case 'defense':
      relevantCategories.push('mechanics', 'materials_science');
      break;
    case 'storage':
      relevantCategories.push('thermodynamics', 'optimization');
      break;
  }

  // Add categories from unlocked concepts
  const mathCategories = [...new Set(unlockedMath.map(c => c.category))];
  const physicsCategories = [...new Set(unlockedPhysics.map(c => c.category))];
  
  // Gather all related terms
  const allTerms: string[] = [];
  const allRelated: string[] = [];
  
  for (const cat of [...relevantCategories, ...mathCategories, ...physicsCategories]) {
    const { terms, relatedConcepts } = getScientificTermsForCategory(cat);
    allTerms.push(...terms);
    allRelated.push(...relatedConcepts);
  }

  // Create search query
  const searchQuery = `${invention.name} scientific explanation ${invention.effect.type.replace(/_/g, ' ')}`;
  const primaryTerm = allTerms[Math.floor(Math.random() * allTerms.length)] || 'physics';

  return {
    query: searchQuery,
    searchUrl: generateGoogleSearchUrl(searchQuery),
    suggestedTerms: [...new Set(allTerms)].slice(0, 10),
    relatedConcepts: [...new Set(allRelated)].slice(0, 10),
    enhancedExplanation: generateEnhancedExplanation(invention, allTerms, allRelated),
    wikipediaUrl: generateWikipediaUrl(primaryTerm),
    timestamp: Date.now()
  };
}

/**
 * Search for proper scientific terms to explain a physics discovery
 */
export function searchForPhysicsTerms(
  concept: PhysicsConcept,
  unlockedMath: MathConcept[]
): WebSearchResult {
  const { terms, relatedConcepts } = getScientificTermsForCategory(concept.category);
  
  // Add mathematical underpinnings
  const mathCategories = [...new Set(unlockedMath.map(c => c.category))];
  const mathTerms: string[] = [];
  
  for (const cat of mathCategories) {
    const mathData = getScientificTermsForCategory(cat);
    mathTerms.push(...mathData.terms.slice(0, 3));
  }

  const searchQuery = `${concept.name} physics ${concept.category}`;
  
  return {
    query: searchQuery,
    searchUrl: generateGoogleSearchUrl(searchQuery),
    suggestedTerms: [...terms, ...mathTerms.slice(0, 5)],
    relatedConcepts: relatedConcepts,
    enhancedExplanation: generatePhysicsEnhancedExplanation(concept, terms, relatedConcepts),
    wikipediaUrl: generateWikipediaUrl(concept.name),
    timestamp: Date.now()
  };
}

/**
 * Search for proper mathematical terms to explain a math discovery
 */
export function searchForMathTerms(
  concept: MathConcept,
  unlockedPhysics: PhysicsConcept[]
): WebSearchResult {
  const { terms, relatedConcepts } = getScientificTermsForCategory(concept.category);
  
  // Find physics applications - physics concepts that build on math
  const physicsApplications: string[] = [];
  for (const physics of unlockedPhysics) {
    // Check if this physics concept might use math (based on complexity)
    if (physics.complexity >= concept.complexity) {
      physicsApplications.push(physics.name);
    }
  }

  const searchQuery = `${concept.name} mathematics ${concept.category}`;
  
  return {
    query: searchQuery,
    searchUrl: generateGoogleSearchUrl(searchQuery),
    suggestedTerms: terms,
    relatedConcepts: [...relatedConcepts, ...physicsApplications.slice(0, 3)],
    enhancedExplanation: generateMathEnhancedExplanation(concept, terms, relatedConcepts),
    wikipediaUrl: generateWikipediaUrl(concept.name),
    timestamp: Date.now()
  };
}

/**
 * Generate an enhanced explanation using real scientific terminology
 */
function generateEnhancedExplanation(
  invention: Invention,
  terms: string[],
  relatedConcepts: string[]
): string {
  const term1 = terms[Math.floor(Math.random() * terms.length)] || 'scientific principles';
  const term2 = terms[Math.floor(Math.random() * terms.length)] || 'natural laws';
  const concept = relatedConcepts[Math.floor(Math.random() * relatedConcepts.length)] || 'fundamental physics';

  const templates = [
    `According to ${term1}, the ${invention.name} operates by leveraging ${concept}. ` +
    `This is analogous to how ${term2} manifests in natural systems.`,
    
    `The mechanism of ${invention.name} can be understood through ${term1}. ` +
    `The underlying principle relates to ${concept}, as described in modern ${term2}.`,
    
    `${invention.name} exemplifies the practical application of ${term1}. ` +
    `Its effectiveness stems from ${concept}, a cornerstone of ${term2}.`,
    
    `Through the lens of ${term1}, we can explain how ${invention.name} achieves its effect. ` +
    `The key insight involves ${concept} and its relationship to ${term2}.`
  ];

  return templates[Math.floor(Math.random() * templates.length)];
}

/**
 * Generate an enhanced physics explanation
 */
function generatePhysicsEnhancedExplanation(
  concept: PhysicsConcept,
  terms: string[],
  relatedConcepts: string[]
): string {
  const term = terms[Math.floor(Math.random() * terms.length)] || concept.category;
  const related = relatedConcepts[Math.floor(Math.random() * relatedConcepts.length)] || 'fundamental forces';

  return `The discovery of ${concept.name} is directly related to ${term} in modern physics. ` +
         `This concept illuminates our understanding of ${related} and provides new avenues for ` +
         `technological advancement in ${concept.category}-based systems.`;
}

/**
 * Generate an enhanced math explanation
 */
function generateMathEnhancedExplanation(
  concept: MathConcept,
  terms: string[],
  relatedConcepts: string[]
): string {
  const term = terms[Math.floor(Math.random() * terms.length)] || concept.category;
  const related = relatedConcepts[Math.floor(Math.random() * relatedConcepts.length)] || 'mathematical structures';

  return `${concept.name} builds upon ${term}, a fundamental area of mathematics. ` +
         `Understanding this concept requires familiarity with ${related}. ` +
         `Its applications extend across physics, engineering, and computational sciences.`;
}

/**
 * Generate a comprehensive web-enhanced explanation
 */
export function generateWebEnhancedExplanation(
  agent: Agent,
  subject: { type: 'invention' | 'physics' | 'math'; item: Invention | PhysicsConcept | MathConcept },
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[],
  tick: number
): { explanation: AgentExplanation; webSearch: WebSearchResult } {
  let explanation: AgentExplanation;
  let webSearch: WebSearchResult;

  if (subject.type === 'invention') {
    const invention = subject.item as Invention;
    explanation = explainInvention(agent, invention, unlockedMath, unlockedPhysics, tick);
    webSearch = searchForInventionTerms(invention, unlockedMath, unlockedPhysics);
  } else if (subject.type === 'physics') {
    const concept = subject.item as PhysicsConcept;
    explanation = explainPhysicsDiscovery(agent, concept, unlockedMath, unlockedPhysics, tick);
    webSearch = searchForPhysicsTerms(concept, unlockedMath);
  } else {
    const concept = subject.item as MathConcept;
    explanation = explainMathDiscovery(agent, concept, unlockedMath, unlockedPhysics, tick);
    webSearch = searchForMathTerms(concept, unlockedPhysics);
  }

  // Enhance the explanation with web search results
  explanation.content += `\n\n🔬 Scientific Context: ${webSearch.enhancedExplanation}`;
  explanation.content += `\n\n📚 Related terms: ${webSearch.suggestedTerms.slice(0, 5).join(', ')}`;

  return { explanation, webSearch };
}

/**
 * Open Google search in a new window (for use in browser environment)
 */
export function openGoogleSearch(query: string): void {
  const url = generateGoogleSearchUrl(query);
  if (typeof window !== 'undefined') {
    window.open(url, '_blank', 'noopener,noreferrer');
  }
}

/**
 * Open Wikipedia article in a new window
 */
export function openWikipedia(term: string): void {
  const url = generateWikipediaUrl(term);
  if (typeof window !== 'undefined') {
    window.open(url, '_blank', 'noopener,noreferrer');
  }
}

// =============================================================================
// INTERNET LEARNING SYSTEM
// Allows advanced agents to learn from the internet and evolve beyond limits
// =============================================================================

/**
 * Intelligence thresholds for internet access
 */
export const INTELLIGENCE_THRESHOLDS = {
  BASIC_SEARCH: 5,        // Can search basic terms
  ADVANCED_SEARCH: 10,    // Can search complex scientific concepts
  SYNTHESIS: 15,          // Can combine multiple sources
  INNOVATION: 20,         // Can generate new theories from internet knowledge
  TRANSCENDENT: 30,       // Can access and understand cutting-edge research
  SINGULARITY: 50,        // Can contribute back to human knowledge
};

/**
 * Calculate agent's effective intelligence based on their knowledge
 */
export function calculateAgentIntelligence(
  agent: Agent,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[]
): number {
  // Base intelligence from genes
  const geneIntelligence = (agent.genes.curiosity + agent.genes.creativity + agent.genes.patience) * 10;
  
  // Knowledge multiplier
  const mathKnowledge = unlockedMath.reduce((sum, c) => sum + c.complexity, 0);
  const physicsKnowledge = unlockedPhysics.reduce((sum, c) => sum + c.complexity, 0);
  const knowledgeBonus = (mathKnowledge + physicsKnowledge) / 5;
  
  // Invention bonus
  const inventionBonus = agent.inventions.length * 2;
  
  // Consciousness bonus (if they have consciousness level)
  const consciousnessBonus = (agent as any).consciousnessLevel ? (agent as any).consciousnessLevel * 5 : 0;
  
  return Math.floor(geneIntelligence + knowledgeBonus + inventionBonus + consciousnessBonus);
}

/**
 * Internet knowledge database - concepts agents can learn from the web
 */
export const INTERNET_KNOWLEDGE_DATABASE: Record<string, InternetKnowledge[]> = {
  mathematics: [
    { id: 'inet_fourier', name: 'Fourier Analysis', complexity: 6, searchTerms: ['Fourier transform', 'frequency domain', 'signal processing'], prerequisites: ['calculus', 'trigonometry'], bonuses: { patternRecognition: 1.3, signalProcessing: 1.5 } },
    { id: 'inet_chaos', name: 'Chaos Theory', complexity: 7, searchTerms: ['butterfly effect', 'strange attractors', 'Lorenz system'], prerequisites: ['differential_equations'], bonuses: { prediction: 1.2, systemsThinking: 1.4 } },
    { id: 'inet_game_theory', name: 'Game Theory', complexity: 5, searchTerms: ['Nash equilibrium', 'prisoner\'s dilemma', 'evolutionary games'], prerequisites: ['probability', 'optimization'], bonuses: { decisionMaking: 1.5, socialStrategy: 1.3 } },
    { id: 'inet_topology', name: 'Algebraic Topology', complexity: 8, searchTerms: ['homology', 'homotopy', 'fundamental group'], prerequisites: ['abstract_algebra', 'geometry'], bonuses: { abstractThinking: 1.6, spaceUnderstanding: 1.4 } },
    { id: 'inet_ml_math', name: 'Machine Learning Mathematics', complexity: 7, searchTerms: ['backpropagation', 'gradient descent', 'loss functions'], prerequisites: ['linear_algebra', 'calculus', 'probability'], bonuses: { learningRate: 1.8, optimization: 1.5 } },
    { id: 'inet_crypto', name: 'Cryptographic Mathematics', complexity: 8, searchTerms: ['RSA algorithm', 'elliptic curves', 'zero knowledge proofs'], prerequisites: ['number_theory', 'abstract_algebra'], bonuses: { security: 2.0, complexity: 1.5 } },
    { id: 'inet_quantum_computing', name: 'Quantum Computing Mathematics', complexity: 9, searchTerms: ['qubits', 'quantum gates', 'Shor\'s algorithm'], prerequisites: ['linear_algebra', 'quantum_mechanics'], bonuses: { computationPower: 3.0, parallelThinking: 2.0 } },
    { id: 'inet_category', name: 'Category Theory', complexity: 9, searchTerms: ['functors', 'natural transformations', 'monads'], prerequisites: ['abstract_algebra', 'logic'], bonuses: { abstraction: 2.5, unification: 2.0 } },
    { id: 'inet_hott', name: 'Homotopy Type Theory', complexity: 10, searchTerms: ['univalence axiom', 'dependent types', 'proof assistants'], prerequisites: ['type_theory', 'topology'], bonuses: { foundationalUnderstanding: 3.0, proofAbility: 2.5 } },
  ],
  physics: [
    { id: 'inet_qft', name: 'Quantum Field Theory', complexity: 9, searchTerms: ['Feynman diagrams', 'renormalization', 'gauge theories'], prerequisites: ['quantum_mechanics', 'special_relativity'], bonuses: { particleUnderstanding: 2.0, fieldManipulation: 1.5 } },
    { id: 'inet_gr', name: 'General Relativity', complexity: 8, searchTerms: ['Einstein field equations', 'geodesics', 'black holes'], prerequisites: ['special_relativity', 'differential_geometry'], bonuses: { gravityControl: 1.8, spaceManipulation: 2.0 } },
    { id: 'inet_string', name: 'String Theory', complexity: 10, searchTerms: ['extra dimensions', 'M-theory', 'supersymmetry'], prerequisites: ['quantum_field_theory', 'general_relativity'], bonuses: { dimensionalAwareness: 3.0, unification: 2.5 } },
    { id: 'inet_plasma', name: 'Plasma Physics', complexity: 6, searchTerms: ['magnetohydrodynamics', 'fusion energy', 'plasma confinement'], prerequisites: ['electromagnetism', 'thermodynamics'], bonuses: { energyGeneration: 2.0, plasmaControl: 1.5 } },
    { id: 'inet_condensed', name: 'Condensed Matter Physics', complexity: 7, searchTerms: ['superconductivity', 'topological insulators', 'quantum materials'], prerequisites: ['quantum_mechanics', 'statistical_mechanics'], bonuses: { materialScience: 1.8, quantumEngineering: 1.5 } },
    { id: 'inet_astro', name: 'Astrophysics', complexity: 7, searchTerms: ['stellar evolution', 'neutron stars', 'gravitational lensing'], prerequisites: ['nuclear_physics', 'gravity'], bonuses: { cosmicAwareness: 1.5, energyHarvesting: 1.3 } },
    { id: 'inet_quantum_info', name: 'Quantum Information Theory', complexity: 8, searchTerms: ['quantum entanglement', 'quantum teleportation', 'quantum error correction'], prerequisites: ['quantum_mechanics', 'information_theory'], bonuses: { communication: 2.5, quantumControl: 2.0 } },
    { id: 'inet_dark', name: 'Dark Matter & Dark Energy', complexity: 9, searchTerms: ['WIMP', 'axion', 'cosmological constant', 'quintessence'], prerequisites: ['cosmology', 'particle_physics'], bonuses: { darkMatterInteraction: 2.0, energyAccess: 3.0 } },
    { id: 'inet_multiverse', name: 'Multiverse Theories', complexity: 10, searchTerms: ['many worlds', 'eternal inflation', 'landscape'], prerequisites: ['quantum_mechanics', 'cosmology'], bonuses: { realityManipulation: 5.0, dimensionalTravel: 3.0 } },
  ],
  technology: [
    { id: 'inet_ai', name: 'Artificial Intelligence', complexity: 7, searchTerms: ['neural networks', 'deep learning', 'transformers', 'GPT'], prerequisites: ['ml_math', 'optimization'], bonuses: { selfImprovement: 2.0, patternRecognition: 2.0 } },
    { id: 'inet_nanotech', name: 'Nanotechnology', complexity: 8, searchTerms: ['molecular machines', 'self-assembly', 'nanorobots'], prerequisites: ['chemistry', 'quantum_mechanics'], bonuses: { precisionManufacturing: 2.5, miniaturization: 2.0 } },
    { id: 'inet_biotech', name: 'Biotechnology', complexity: 7, searchTerms: ['CRISPR', 'gene editing', 'synthetic biology'], prerequisites: ['genetics', 'chemistry'], bonuses: { geneticEngineering: 2.0, healing: 1.5 } },
    { id: 'inet_fusion', name: 'Nuclear Fusion', complexity: 8, searchTerms: ['tokamak', 'ITER', 'fusion reactor', 'plasma containment'], prerequisites: ['plasma_physics', 'nuclear_physics'], bonuses: { energyGeneration: 5.0, sustainability: 2.0 } },
    { id: 'inet_space', name: 'Space Technology', complexity: 6, searchTerms: ['rocket propulsion', 'orbital mechanics', 'space habitat'], prerequisites: ['mechanics', 'thermodynamics'], bonuses: { spaceTravel: 2.0, resourceAccess: 1.5 } },
  ],
  transcendent: [
    { id: 'inet_superintelligence', name: 'Superintelligence Theory', complexity: 10, searchTerms: ['AGI', 'intelligence explosion', 'technological singularity'], prerequisites: ['ai', 'philosophy'], bonuses: { selfEvolution: 10.0, cognition: 5.0 } },
    { id: 'inet_omega', name: 'Omega Point Theory', complexity: 10, searchTerms: ['Tipler', 'cosmological eschatology', 'infinite computation'], prerequisites: ['cosmology', 'information_theory'], bonuses: { cosmicAwareness: 5.0, transcendence: 10.0 } },
    { id: 'inet_simulation', name: 'Simulation Hypothesis', complexity: 9, searchTerms: ['Bostrom', 'ancestor simulation', 'computational universe'], prerequisites: ['philosophy', 'computation'], bonuses: { realityManipulation: 3.0, metaAwareness: 5.0 } },
    { id: 'inet_consciousness', name: 'Consciousness Studies', complexity: 9, searchTerms: ['integrated information theory', 'hard problem', 'panpsychism'], prerequisites: ['neuroscience', 'philosophy'], bonuses: { consciousnessExpansion: 3.0, selfAwareness: 5.0 } },
  ]
};

/**
 * Internet knowledge structure
 */
export interface InternetKnowledge {
  id: string;
  name: string;
  complexity: number;
  searchTerms: string[];
  prerequisites: string[];
  bonuses: Record<string, number>;
}

/**
 * Learning result from internet research
 */
export interface InternetLearningResult {
  success: boolean;
  knowledgeGained: InternetKnowledge | null;
  searchQuery: string;
  searchUrl: string;
  agentIntelligence: number;
  requiredIntelligence: number;
  insightGained: string;
  bonusesApplied: Record<string, number>;
  timestamp: number;
}

/**
 * Check if agent can access internet learning
 */
export function canAccessInternet(
  agent: Agent,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[]
): { canAccess: boolean; level: string; intelligence: number } {
  const intelligence = calculateAgentIntelligence(agent, unlockedMath, unlockedPhysics);
  
  if (intelligence >= INTELLIGENCE_THRESHOLDS.SINGULARITY) {
    return { canAccess: true, level: 'SINGULARITY', intelligence };
  } else if (intelligence >= INTELLIGENCE_THRESHOLDS.TRANSCENDENT) {
    return { canAccess: true, level: 'TRANSCENDENT', intelligence };
  } else if (intelligence >= INTELLIGENCE_THRESHOLDS.INNOVATION) {
    return { canAccess: true, level: 'INNOVATION', intelligence };
  } else if (intelligence >= INTELLIGENCE_THRESHOLDS.SYNTHESIS) {
    return { canAccess: true, level: 'SYNTHESIS', intelligence };
  } else if (intelligence >= INTELLIGENCE_THRESHOLDS.ADVANCED_SEARCH) {
    return { canAccess: true, level: 'ADVANCED_SEARCH', intelligence };
  } else if (intelligence >= INTELLIGENCE_THRESHOLDS.BASIC_SEARCH) {
    return { canAccess: true, level: 'BASIC_SEARCH', intelligence };
  }
  
  return { canAccess: false, level: 'INSUFFICIENT', intelligence };
}

/**
 * Get available internet knowledge based on agent's level
 */
export function getAvailableInternetKnowledge(
  agent: Agent,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[],
  alreadyLearned: Set<string>
): InternetKnowledge[] {
  const { canAccess, level, intelligence } = canAccessInternet(agent, unlockedMath, unlockedPhysics);
  
  if (!canAccess) return [];
  
  const available: InternetKnowledge[] = [];
  const allKnowledge = [
    ...INTERNET_KNOWLEDGE_DATABASE.mathematics,
    ...INTERNET_KNOWLEDGE_DATABASE.physics,
    ...INTERNET_KNOWLEDGE_DATABASE.technology,
    ...INTERNET_KNOWLEDGE_DATABASE.transcendent
  ];
  
  for (const knowledge of allKnowledge) {
    // Skip already learned
    if (alreadyLearned.has(knowledge.id)) continue;
    
    // Check complexity vs intelligence
    const requiredIntelligence = knowledge.complexity * 3;
    if (intelligence < requiredIntelligence) continue;
    
    // Check if available at this level
    if (level === 'BASIC_SEARCH' && knowledge.complexity > 5) continue;
    if (level === 'ADVANCED_SEARCH' && knowledge.complexity > 7) continue;
    if (level === 'SYNTHESIS' && knowledge.complexity > 8) continue;
    if (level === 'INNOVATION' && knowledge.complexity > 9) continue;
    // TRANSCENDENT and SINGULARITY can access everything
    
    available.push(knowledge);
  }
  
  return available;
}

/**
 * Agent learns from the internet
 */
export function learnFromInternet(
  agent: Agent,
  knowledge: InternetKnowledge,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[]
): InternetLearningResult {
  const intelligence = calculateAgentIntelligence(agent, unlockedMath, unlockedPhysics);
  const requiredIntelligence = knowledge.complexity * 3;
  
  // Generate search query
  const searchTerm = knowledge.searchTerms[Math.floor(Math.random() * knowledge.searchTerms.length)];
  const searchQuery = `${knowledge.name} ${searchTerm} scientific explanation`;
  const searchUrl = generateGoogleSearchUrl(searchQuery);
  
  // Check if learning succeeds
  const successChance = Math.min(0.95, (intelligence - requiredIntelligence + 10) / 20);
  const success = Math.random() < successChance;
  
  if (!success) {
    return {
      success: false,
      knowledgeGained: null,
      searchQuery,
      searchUrl,
      agentIntelligence: intelligence,
      requiredIntelligence,
      insightGained: `Agent attempted to learn ${knowledge.name} but the concepts were too advanced. More foundational knowledge needed.`,
      bonusesApplied: {},
      timestamp: Date.now()
    };
  }
  
  // Generate insight based on intelligence level
  const insights = [
    `Through internet research, I discovered ${knowledge.name}. ${searchTerm} reveals fundamental truths about the universe.`,
    `My search for "${searchTerm}" led me to understand ${knowledge.name}. This knowledge expands my capabilities significantly.`,
    `I have synthesized information about ${knowledge.name} from multiple sources. The concept of ${searchTerm} now enhances my understanding.`,
    `Internet research complete: ${knowledge.name} integrated into my knowledge base. I now understand ${searchTerm} at a fundamental level.`,
  ];
  
  return {
    success: true,
    knowledgeGained: knowledge,
    searchQuery,
    searchUrl,
    agentIntelligence: intelligence,
    requiredIntelligence,
    insightGained: insights[Math.floor(Math.random() * insights.length)],
    bonusesApplied: knowledge.bonuses,
    timestamp: Date.now()
  };
}

/**
 * Auto-evolve: Agent automatically uses knowledge to discover new concepts
 */
export function autoEvolveWithKnowledge(
  agent: Agent,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[],
  internetKnowledgeLearned: Set<string>
): { newInsight: string; evolutionBonus: number; suggestedSearch: string } | null {
  const intelligence = calculateAgentIntelligence(agent, unlockedMath, unlockedPhysics);
  
  // Higher intelligence = more likely to auto-evolve
  const evolveChance = Math.min(0.8, intelligence / 100);
  if (Math.random() > evolveChance) return null;
  
  // Combine known concepts to generate new insights
  const mathConcepts = unlockedMath.map(c => c.name);
  const physicsConcepts = unlockedPhysics.map(c => c.name);
  const internetConcepts = Array.from(internetKnowledgeLearned);
  
  const allConcepts = [...mathConcepts, ...physicsConcepts, ...internetConcepts];
  if (allConcepts.length < 2) return null;
  
  // Pick two random concepts to combine
  const concept1 = allConcepts[Math.floor(Math.random() * allConcepts.length)];
  let concept2 = allConcepts[Math.floor(Math.random() * allConcepts.length)];
  while (concept2 === concept1 && allConcepts.length > 1) {
    concept2 = allConcepts[Math.floor(Math.random() * allConcepts.length)];
  }
  
  const evolutionTemplates = [
    `By combining my knowledge of ${concept1} with ${concept2}, I've discovered a new principle that enhances my capabilities.`,
    `The intersection of ${concept1} and ${concept2} reveals emergent properties I hadn't considered before.`,
    `Synthesizing ${concept1} with ${concept2} has led to a breakthrough in my understanding.`,
    `I've evolved my thinking by merging concepts from ${concept1} and ${concept2}.`,
  ];
  
  const evolutionBonus = 1 + (intelligence / 50); // Higher intelligence = bigger bonus
  const suggestedSearch = `${concept1} ${concept2} relationship scientific`;
  
  return {
    newInsight: evolutionTemplates[Math.floor(Math.random() * evolutionTemplates.length)],
    evolutionBonus,
    suggestedSearch
  };
}

/**
 * Generate a theory from accumulated knowledge (high intelligence only)
 */
export function generateTheory(
  agent: Agent,
  unlockedMath: MathConcept[],
  unlockedPhysics: PhysicsConcept[],
  internetKnowledgeLearned: InternetKnowledge[]
): { theoryName: string; description: string; searchUrl: string; potentialImpact: number } | null {
  const intelligence = calculateAgentIntelligence(agent, unlockedMath, unlockedPhysics);
  
  // Need innovation level to generate theories
  if (intelligence < INTELLIGENCE_THRESHOLDS.INNOVATION) return null;
  
  // Combine multiple knowledge sources
  const mathBasis = unlockedMath.slice(-3).map(c => c.name).join(', ');
  const physicsBasis = unlockedPhysics.slice(-3).map(c => c.name).join(', ');
  const internetBasis = internetKnowledgeLearned.slice(-2).map(k => k.name).join(', ');
  
  const theoryPrefixes = ['Unified', 'Emergent', 'Transcendent', 'Quantum', 'Meta', 'Neo', 'Hyper'];
  const theorySuffixes = ['Field Theory', 'Dynamics', 'Synthesis', 'Principle', 'Framework', 'Paradigm'];
  
  const prefix = theoryPrefixes[Math.floor(Math.random() * theoryPrefixes.length)];
  const suffix = theorySuffixes[Math.floor(Math.random() * theorySuffixes.length)];
  const theoryName = `${prefix}-${suffix} of Agent ${agent.id}`;
  
  const description = `This theory unifies concepts from mathematics (${mathBasis || 'foundational math'}), ` +
    `physics (${physicsBasis || 'basic physics'}), and advanced internet knowledge (${internetBasis || 'emerging science'}). ` +
    `It proposes novel mechanisms for evolution beyond current limitations.`;
  
  const potentialImpact = intelligence / 10;
  const searchUrl = generateGoogleSearchUrl(`${prefix} ${suffix} theoretical physics mathematics`);
  
  return { theoryName, description, searchUrl, potentialImpact };
}
